Settings
tyler-dot-earth/obsidian-blockreffer pull request #7
Opened 2024-10-22 01:56 UTC by GuardKenzie

This pull request adds settings for all the items marked as `//TODO` as well as some quality of life settings of my own. Users can now specify
- How many blocks to display in the search results
- Which of a blocks contents, file name or block ids should be indexed by the search
- If to remove the actual ^block-id text from the block contents in search results
- Whether to display file names as their full path or just their base name
- Whether or not to parse markdown links in block contents
- The format of the inserted reference, which defaults to `!{link}`
- If the selected text should be used as the display text for the reference link
- If to use the selected text as the initial search query when search is opened

<details>
<summary>📸 Here's a screenshot of the settings menu</summary>
<br>
<div align="center">
  <img width="500" alt="Screenshot 2024-10-22 at 03 51 49" src="https://github.com/user-attachments/assets/1f5b3223-820a-4e0b-a31c-394097e69818">
</div>
</details

I tried to follow the style of the current code but I may have missed some semicolons hehe.

Best,
Erica 🧡

2024-10-23 00:33 UTC, tyler-dot-earth commented
Wow, @GuardKenzie - incredible contribution! Thank you so much for your work on this. Absolutely above and beyond haha.

I'll give it a test and review this week(end) :saluting_face:

2024-10-26 00:52 UTC, tyler-dot-earth requested changes
Tested and reviewed the code - awesome work.

Left a few comments - they're almost entirely related to phrasing. Left a couple phrasing questions to see what you think as well. I also included suggested changes that can easily be committed when possible.

And thanks again. You've already done a lot, so let me know if you'd like me to make these changes.

Looking forward to merging and releasing this :slightly_smiling_face:

2024-10-26 00:52 UTC, tyler-dot-earth commented on settings/settingsTab.ts
> +				.setPlaceholder('!{link}')
let's handle the case of someone clearing the input - for example, fallback to default value.

2024-10-26 00:52 UTC, tyler-dot-earth commented on settings/settingsTab.ts
> +			.setDesc('How your link will be inserted into the document. Use {link} as a placeholder for the actual link.')
no action needed / just thinking out loud / note to self:

probably just a me thing, but the phrasing doesn't feel intuitive to me as i don't think about embeds as links despite the fact that embeds are made *from* links.

that said, i have no better suggestion for now :cowboy_hat_face:

2024-10-26 00:52 UTC, tyler-dot-earth commented on main.ts
> +		if (this.plugin.settings.toSearch.content) toSearch += item.content;
relatively inconsequential, but noting that this content will contain the `^block-id` which can still be searched even if `toSearch.id === false`.

2024-10-26 00:52 UTC, tyler-dot-earth commented on settings/settings.ts
> +}
opportunity for some tsdocs

```suggestion
export interface BlockrefferSettings {
    /** The format string for inserting a backlink.
     * @example `!{link}` becomes `![[link]]
     */
    format: string;

    /** Whether the selected text should be retained as the link display text. */
    keepText: boolean;

    /** Whether links should be parsed using the `unlinkfy` method. */
    parseLinks: boolean;

    /** Uses the selected text as the initial search value. */
    selectedTextAsSearch: boolean;

    /** Specifies content that should be searched. */
    toSearch: {
        /** Whether to search within file content. */
        content: boolean;

        /** Whether to search for matches in the file path. */
        path: boolean;

        /** Whether to search for matches by file ID. */
        id: boolean;
    };

    /** Maximum number of search results to display. */
    searchLimit: number;

    /** Whether to remove `^block-id` from the content. */
    removeIdFromContent: boolean;

    /** How the file name should be displayed: "path" for full path or "base" for name only. */
    fileName: "path" | "base";
}
```

2024-10-26 00:52 UTC, tyler-dot-earth commented on settings/settingsTab.ts
> +        /* === What to search */
:pinching_hand: tiny consistency with above
```suggestion
        /* === What to search === */
```

2024-10-26 00:52 UTC, tyler-dot-earth commented on settings/settingsTab.ts
> +            .setDesc("Search for file names")
```suggestion
            .setDesc("Search file path and name.")
```

2024-10-26 00:52 UTC, tyler-dot-earth commented on settings/settingsTab.ts
> +            .setDesc("Search for ^block-ids")
```suggestion
            .setDesc("Search ^block-ids.")
```

2024-10-26 00:52 UTC, tyler-dot-earth commented on settings/settingsTab.ts
> +            .setDesc("Search for text inside blocks.")
```suggestion
            .setDesc("Search text inside blocks.")
```

2024-10-26 00:52 UTC, tyler-dot-earth commented on settings/settings.ts
> +	format: '!{link}',
thoughts on `{backlink}` instead of `link`?

when i see `link` i think `[]()`

2024-10-26 00:52 UTC, tyler-dot-earth commented on settings/settings.ts
> +    fileName: "base"
```suggestion
    fileName: "base" as const,
```

2024-10-26 00:52 UTC, tyler-dot-earth commented on settings/settingsTab.ts
> +			.setDesc('How your link will be inserted into the document. Use {link} as a placeholder for the actual link.')
followup after more review:

per one of the other comments ...
> when i see `link` i think `[]()`

... maybe: `backlink` instead of `link`?

2024-10-26 00:52 UTC, tyler-dot-earth commented on settings/settingsTab.ts
> +            .setDesc("If true, will use the text you have selected as the display text for the link (the bit that goes after the | symbol).")
i like the character you added with "the bit" :sparkles: 

```suggestion
            .setDesc("Use selected text as the link alias (the bit that goes after the | symbol).")
```

2024-10-26 00:52 UTC, tyler-dot-earth commented on settings/settingsTab.ts
> +                .setDesc("Should the ^block-id text be removed from the block contents in search results (it will still be displayed beneath the block contents).")
```suggestion
                .setDesc("Do not display the ^block-id in search results. It will still be displayed beneath the block contents.")
```

2024-10-26 00:52 UTC, tyler-dot-earth commented on settings/settingsTab.ts
> +            .setDesc("If true, when you open the search box, the text you have selected will already be searched for.")
```suggestion
            .setDesc("If true, selected text will be used when you open the search box.")
```

2024-10-26 00:52 UTC, tyler-dot-earth commented on settings/settingsTab.ts
> +                .addOption("path", "File path")
shortens phrasing + matches the sentence order to option order
```suggestion
            .setDesc("Show just the filename or their/full/path.md in search results?")
            .addDropdown(dropdown => dropdown
                .addOption("base", "File name")
                .addOption("path", "File path")
```

2024-10-26 02:02 UTC, GuardKenzie commented
Thanks for the thorough review! I'll take a look at these after the weekend 🧡

2024-10-31 15:23 UTC, GuardKenzie commented on settings/settingsTab.ts
> +            .setDesc("If true, will use the text you have selected as the display text for the link (the bit that goes after the | symbol).")
Hahaha thanks. I didn't know how else to explain it without it being overly complicated 😂

2024-10-31 17:33 UTC, GuardKenzie commented on settings/settingsTab.ts
> +				.setPlaceholder('!{link}')
This has been added in 7272ad0e6cf869274df131aa9ddb59836fc80061 along with a red border to indicate that no `!{link}` placeholder is present

2024-10-31 17:39 UTC, GuardKenzie commented on settings/settingsTab.ts
> +			.setDesc('How your link will be inserted into the document. Use {link} as a placeholder for the actual link.')
Good call. Resolved in 72d5cca9ad55dc0a2fd1e873cea51ff86d7567e7

2024-10-31 17:42 UTC, GuardKenzie commented on settings/settings.ts
> +	format: '!{link}',
This is a good idea, especially since the settings already reference the standrd "link" i.e. hyperlinks. Resolved in 5ead9c9e03e0ae715590a8db795d8fe6baef9704

2024-10-31 17:46 UTC, GuardKenzie commented on main.ts
> +		if (this.plugin.settings.toSearch.content) toSearch += item.content;
Resolved with 046a5906b7563e3599d044f401899533e9b408ca. I just erased the ^block-id from `item.content` like is done in the main search function.

2024-11-17 18:26 UTC, tyler-dot-earth approved these changes
Thank you so much for the contribution, updates, and patience! Gonna prepare a release with this right now :)

2024-11-17 18:27 UTC, merged